apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
spec:
  # 定义容器，可以多个
  containers:
    - name: nodeapp # 容器名字
      imagePullPolicy: IfNotPresent
      image: nodeapp:latest # 镜像
      ports: # 设置容器暴露的端口列表
        - name: nodeapp-port
          containerPort: 8081
          protocol: TCP
